# Generated by Django 4.1 on 2024-07-19 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IpData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=17, unique=True, verbose_name='服务器')),
                ('ping', models.FloatField(max_length=6, verbose_name='延迟ms')),
                ('speed', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='速度')),
                ('uptime1', models.CharField(max_length=5, verbose_name='上传时间1')),
                ('uptime2', models.CharField(max_length=5, verbose_name='上传时间2')),
                ('server_type', models.CharField(max_length=20, verbose_name='类型')),
                ('country', models.CharField(max_length=20, verbose_name='国家')),
                ('ssl', models.BooleanField(verbose_name='SSL')),
                ('connect', models.BooleanField(verbose_name='CONN.')),
                ('post', models.BooleanField(verbose_name='POST')),
                ('last_work_time', models.BooleanField(verbose_name='最近工作时间')),
            ],
        ),
    ]
