# Generated by Django 4.1 on 2024-07-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='connect',
            field=models.CharField(max_length=20, verbose_name='CONN.'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='last_work_time',
            field=models.CharField(max_length=20, verbose_name='最近工作时间'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='post',
            field=models.CharField(max_length=20, verbose_name='POST'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(max_length=20, verbose_name='SSL'),
        ),
    ]
