# Generated by Django 4.1 on 2024-07-19 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_alter_ipdata_connect_alter_ipdata_last_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='ping',
            field=models.DecimalField(decimal_places=4, max_digits=6, verbose_name='延迟ms'),
        ),
    ]
