# Generated by Django 4.1 on 2024-07-23 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_ipdata_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ipdata',
            old_name='connect',
            new_name='conn',
        ),
        migrations.RenameField(
            model_name='ipdata',
            old_name='server_type',
            new_name='type_data',
        ),
    ]
