# Generated by Django 4.1 on 2024-07-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_rename_connect_ipdata_conn_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='server',
            field=models.CharField(max_length=21, unique=True, verbose_name='服务器'),
        ),
    ]
