# Generated by Django 4.1 on 2024-07-23 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_ipdata_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='conn',
            field=models.CharField(max_length=30, verbose_name='CONN.'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='last_work_time',
            field=models.CharField(max_length=30, verbose_name='最近工作时间'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='post',
            field=models.CharField(max_length=30, verbose_name='POST'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(max_length=30, verbose_name='SSL'),
        ),
    ]
