# Generated by Django 4.1 on 2024-07-23 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0007_alter_ipdata_conn_alter_ipdata_last_work_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='conn',
            field=models.CharField(max_length=50, verbose_name='CONN.'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='post',
            field=models.CharField(max_length=50, verbose_name='POST'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(max_length=50, verbose_name='SSL'),
        ),
    ]
