# Generated by Django 4.1 on 2024-07-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0008_alter_ipdata_conn_alter_ipdata_post_alter_ipdata_ssl'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipdata',
            name='conn',
            field=models.CharField(default='N/A', max_length=50, verbose_name='CONN.'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='country',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='last_work_time',
            field=models.CharField(default='N/A', max_length=30, verbose_name='最近工作时间'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ping',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='延迟ms'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='post',
            field=models.CharField(default='N/A', max_length=50, verbose_name='POST'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='server',
            field=models.CharField(default='Unknown Server', max_length=21, unique=True, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(default='N/A', max_length=50, verbose_name='SSL'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='type_data',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='类型'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='uptime1',
            field=models.CharField(default='N/A', max_length=5, verbose_name='上传时间1'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='uptime2',
            field=models.CharField(default='N/A', max_length=5, verbose_name='上传时间2'),
        ),
    ]
