# Generated by Django 4.1 on 2025-03-22 21:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0010_captcha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='电影名称')),
                ('director', models.CharField(max_length=100, verbose_name='导演')),
                ('actors', models.TextField(verbose_name='主演')),
                ('year', models.CharField(max_length=20, verbose_name='上映年份')),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='评分')),
                ('rating_count', models.IntegerField(verbose_name='评分人数')),
                ('genre', models.CharField(max_length=100, verbose_name='类型')),
                ('region', models.CharField(max_length=100, verbose_name='国家/地区')),
                ('duration', models.CharField(max_length=50, verbose_name='片长')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '电影',
                'verbose_name_plural': '电影',
                'ordering': ['-rating', '-rating_count'],
            },
        ),
        migrations.DeleteModel(
            name='Captcha',
        ),
        migrations.AlterModelOptions(
            name='ipdata',
            options={'ordering': ['-score', '-updated_at'], 'verbose_name': 'IP池', 'verbose_name_plural': 'IP池'},
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='ping',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='post',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='type_data',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='uptime1',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='uptime2',
        ),
        migrations.AddField(
            model_name='ipdata',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='delay',
            field=models.IntegerField(default=0, verbose_name='延迟ms'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='type',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='upload_time1',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间1'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='upload_time2',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间2'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='country',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='last_work_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最近工作时间'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='score',
            field=models.IntegerField(default=0, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='server',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='speed',
            field=models.CharField(default='0 MB/s', max_length=50, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(default='N/A', max_length=10, verbose_name='SSL'),
        ),
    ]
