# Generated by Django 4.1 on 2025-03-22 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0011_movie_delete_captcha_alter_ipdata_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipdata',
            name='delay',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='type',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='upload_time1',
        ),
        migrations.RemoveField(
            model_name='ipdata',
            name='upload_time2',
        ),
        migrations.AddField(
            model_name='ipdata',
            name='ping',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=6, null=True, verbose_name='延迟ms'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='post',
            field=models.CharField(default='N/A', max_length=50, verbose_name='POST'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='type_data',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='类型'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='uptime1',
            field=models.CharField(default='N/A', max_length=5, verbose_name='上传时间1'),
        ),
        migrations.AddField(
            model_name='ipdata',
            name='uptime2',
            field=models.CharField(default='N/A', max_length=5, verbose_name='上传时间2'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='country',
            field=models.CharField(default='Unknown', max_length=20, verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='last_work_time',
            field=models.CharField(default='N/A', max_length=30, verbose_name='最近工作时间'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='score',
            field=models.IntegerField(default=100, verbose_name='分数'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='server',
            field=models.CharField(default='Unknown Server', max_length=21, unique=True, verbose_name='服务器'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='速度'),
        ),
        migrations.AlterField(
            model_name='ipdata',
            name='ssl',
            field=models.CharField(default='N/A', max_length=50, verbose_name='SSL'),
        ),
    ]
