# Generated by Django 5.1.7 on 2025-03-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0014_alter_proxysettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysettings',
            name='auto_crawler',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proxysettings',
            name='auto_score',
            field=models.BooleanField(default=False),
        ),
    ]
