# Generated by Django 5.1.7 on 2025-03-26 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0015_proxysettings_auto_crawler_proxysettings_auto_score'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoubanSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('crawl_interval', models.IntegerField(default=60, help_text='采集间隔（分钟）')),
                ('movie_count', models.IntegerField(default=10, help_text='电影采集数量')),
                ('tv_count', models.IntegerField(default=5, help_text='电视剧采集数量')),
            ],
            options={
                'verbose_name': '豆瓣设置',
                'verbose_name_plural': '豆瓣设置',
            },
        ),
    ]
