# Generated by Django 4.2.20 on 2025-04-03 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0017_movie_poster_url_movie_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_published',
            field=models.BooleanField(default=False, verbose_name='是否已发表'),
        ),
    ]
