# Generated by Django 4.2.20 on 2025-04-03 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0018_movie_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='proxysettings',
            name='captcha_retries',
            field=models.IntegerField(default=5),
        ),
    ]
