# Generated by Django 4.2.20 on 2025-04-03 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0019_proxysettings_captcha_retries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='合集标题')),
                ('description', models.TextField(blank=True, null=True, verbose_name='合集描述')),
                ('collection_type', models.CharField(choices=[('movie', '电影合集'), ('tv', '剧集合集'), ('article', '文章合集'), ('mixed', '混合合集')], default='movie', max_length=20, verbose_name='合集类型')),
                ('cover_image', models.URLField(blank=True, null=True, verbose_name='封面图片URL')),
                ('is_published', models.BooleanField(default=False, verbose_name='是否发布')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('movies', models.ManyToManyField(blank=True, related_name='collections', to='index.movie', verbose_name='电影列表')),
            ],
            options={
                'verbose_name': '合集',
                'verbose_name_plural': '合集列表',
                'ordering': ['-updated_at'],
            },
        ),
    ]
