"""
Django settings for CollectIp project.

Generated by 'django-admin startproject' using Django 4.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2ockpy=7#hbuh4!a=01@we$*vko#j-xp$4w+9w73u+!u#ml)55'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'index',
    'ip_operator.apps.IpOperatorConfig',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'CollectIp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'CollectIp.wsgi.application'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'collectipdb',
        'USER': 'root',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '3306',

    }
}

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'zh-Hans'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/

STATIC_URL = '/static/'

# 静态文件目录列表
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'templates', 'static'),
]

# 生产环境收集静态文件的目录
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# 设置媒体文件的根目录（存储图片等文件的位置）
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 设置媒体文件的 URL（访问图片等文件的 URL 前缀）
MEDIA_URL = '/media/'

# 登录相关配置
LOGIN_URL = '/login/'  # 未登录时重定向到登录页面
LOGIN_REDIRECT_URL = '/ip_pool/'  # 登录成功后重定向到IP池页面
LOGOUT_REDIRECT_URL = '/login/'  # 登出后重定向到登录页面

# 会话配置
SESSION_COOKIE_AGE = 1209600  # 两周
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 关闭浏览器后是否清除session

# IP池配置
IP_POOL_CONFIG = {
    'CRAWLER_INTERVAL': 3600,  # 爬虫间隔（秒）
    'SCORE_INTERVAL': 1800,    # 评分间隔（秒）
    'MIN_SCORE': 10,          # 最低分数
    'TEST_URLS': [
        'http://www.baidu.com',
        'http://www.qq.com',
    ],
    # 添加爬虫配置
    'CRAWLER': {
        'USER_AGENT': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36',
        'DOWNLOAD_DELAY': 2,
        'CONCURRENT_REQUESTS': 16,
    }
}

# 确保logs目录存在
if not os.path.exists(os.path.join(BASE_DIR, 'logs')):
    os.makedirs(os.path.join(BASE_DIR, 'logs'))

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'ip_operator': {
            'level': 'INFO',
            'class': 'logging.handlers.TimedRotatingFileHandler',  # 使用时间轮转处理器
            'filename': os.path.join(BASE_DIR, 'logs', 'ip_operator.log'),
            'formatter': 'verbose',
            'when': 'midnight',  # 每天午夜进行轮转
            'interval': 1,       # 每1天轮转一次
            'backupCount': 3,    # 保留3个备份文件
            'encoding': 'utf-8', # 使用utf-8编码
        },
    },
    'loggers': {
        'ip_operator': {
            'handlers': ['ip_operator'],
            'level': 'INFO',
            'propagate': True,
        },
    },
}

# 在开发环境中启用debug工具栏
if DEBUG:
    INTERNAL_IPS = [
        '127.0.0.1',
    ]
